<?php

namespace mowzs\lib\filesystem\driver;

use League\Flysystem\AdapterInterface;
use Overtrue\Flysystem\Qiniu\QiniuAdapter;
use mowzs\lib\db\exception\DataNotFoundException;
use mowzs\lib\db\exception\DbException;
use mowzs\lib\db\exception\ModelNotFoundException;
use mowzs\lib\filesystem\Driver;

class Qiniu extends Driver
{

    protected function createAdapter(): AdapterInterface
    {
        // TODO: Implement createAdapter() method.
        $qiniuConfig = [
            'access_key' => sys_config('qiniu_access'),
            'secret_key' => sys_config('qiniu_secret'),
            'bucket' => sys_config('qiniu_bucket'),
            'domain' => sys_config('qiniu_domain'),
        ];

        return new QiniuAdapter($qiniuConfig['access_key'], $qiniuConfig['secret_key'], $qiniuConfig['bucket'], $qiniuConfig['domain']);
    }

    /**
     * @param string $path
     * @return string
     * @throws DataNotFoundException
     * @throws DbException
     * @throws ModelNotFoundException
     */
    public function url(string $path): string
    {
        $path = str_replace('\\', '/', $path);

        if (!empty(sys_config('qiniu_domain'))) {
            return $this->concatPathToUrl(sys_config('qiniu_domain'), $path);
        }
        return parent::url($path); // TODO: Change the autogenerated stub
    }
}
