<?php
declare(strict_types=1);

namespace mowzs\lib\module\controller\home;

use app\common\controllers\BaseHome;
use mowzs\lib\module\service\ContentBaseService;

class ContentHome extends BaseHome
{
    /**
     * 服务类名称
     * @var string
     */
    protected static string $serviceClass;
    /**
     * 服务类
     * @var ContentBaseService|mixed
     */
    protected ContentBaseService $service;

    protected function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (empty(static::$serviceClass)) {
            throw new \InvalidArgumentException('The $serviceClass must be set in the subclass.');
        }
        $this->service = new static::$serviceClass();
    }

    /**
     * 内容详情
     * @param int $id
     * @return string
     */
    public function index(int $id = 0): string
    {
        if (empty($id)) {
            $this->error('内容ID不能为空');
        }
        try {
            $info = $this->service->getInfo($id, true);
            if (empty($info)) {
                $this->error('内容不存在');
            }
            if ($info['status'] <= 0) {
                $this->error('内容审核中');
            }
        } catch (\Exception $e) {
            $this->error('出错了!');
        }

        $this->assign([
            'info' => $info,
            'id' => $id,
            'cid' => $info['cid'],
        ]);
        return $this->fetch();
    }

    protected function addView($id, $mid = 0)
    {

    }
}
